### ISSUE TITLE
Variables "now" and "data" not defined in mic callback which throws an error during runtime

### ISSUE THREAD

**Issue by codeobsession** [ViennaMike/ChatterPi#16]
Tried running the code with the test setup for the chatterpi skull project. Servo motion is as expected from file input. When I switch to mic input, the interpreter complained about a couple errors in the code:

1. "now" is not defined in the mic callback
2. "data" is not defined in the mic callback

It looks like code from the files callback may have been cut and pasted into the mic callback and not tested?

Also, the conditional in the mic callback testing for two channels should be removed because the number of channels is set to 1 right above it so it will never get called.

Update 2/12/2024. I was able to get the mic working properly by setting now = time.monotonic() and changing data to in_data in the mic callback...basically following a similar pattern as found in the file callback. 

I see below that you've fixed the issue. I will download your new code and test. Thanks for the quick response! Having a ton of fun getting the skull working. It still needs a bit of tweaking in terms of servo limits and such, but off to a good start. 

Btw, I'm using a Raspberry Pi 4B with the latest 64 bit OS.

**Comment by ViennaMike** [comment]
Thanks for the bug report. You are correct that I didn't have a microphone set up handy, so didn't fully test the last update. I've fixed and tested it todayt, and will upload the fix to GitHub in a day or two.

**Comment by ViennaMike** [comment]
The code has been corrected, tested, and the source code uploaded. Please let me know if you get a chance to test it. I'll keep this issue open until I get a chance to also update the image file.

**Comment by codeobsession** [comment]
I tested the new audio.py file and the mic callback worked as expected.

**Comment by ViennaMike** [comment]
Thanks! At some point all was tested, but as I mentioned, when I last updated audio.py I didn't test the mic update. Glad all is good now. If you find any other bugs, be sure to post them. 

I've also now uploaded the fixed img. file, so I'll close this issue.
